CREATE TABLE TlcProject.materialsTable (
	idmaterialsTable INT NOT NULL PRIMARY KEY,
	material VARCHAR(45) NULL,
	quality VARCHAR(45) NULL
);

INSERT INTO TlcProject.materialsTable (idmaterialsTable, material, quality)
VALUES 
  (1, 'cupro', 'low'),
  (2, 'cupra', 'low'),
  (3, 'rayon', 'low'),
  (4, 'polyester', 'low'),
  (5, 'nylon', 'low'),
  (6, 'cotton', 'low'),
  (7, 'viscose', 'low'),
  (8, 'elastane', 'low'),
  (9, 'econyl', 'good'),
  (10, 'recycled polyester', 'good'),
  (11, 'Modal', 'good'),
  (12, 'Sheep Wool', 'good'),
  (13, 'Merino Wool', 'good'),
  (14, 'Cashmere', 'good'),
  (15, 'Upcycled Leather', 'good'),
  (16, 'Down', 'good'),
  (17, 'Silk', 'good'),
  (18, 'recycled cotton', 'good'),
  (19, 'Vegetable Tanned Leather', 'good'),
  (20, 'hemp', 'high'),
  (21, 'linen', 'high'),
  (22, 'organic cotton', 'high'),
  (23, 'bamboo linen', 'high'),
  (24, 'deadstock', 'high'),
  (25, 'tencel', 'high'),
  (26, 'Bamboo Lyocell', 'high'),
  (27, 'ecovero', 'high'),
  (28, 'Piñatex', 'high'),
  (29, 'Bananatex', 'high'),
  (30, 'Scoby Leather', 'high'),
  (31, 'S.Cafe', 'high'),
  (32, 'Brewed Protein', 'high'),
  (33, 'Apple Leather', 'high'),
  (34, 'Woocoa', 'high'),
  (35, 'QMilk', 'high'),
  (36, 'Alpaca wool', 'high'),
  (37, 'Camel wool', 'high'),
  (38, 'Yak Wool', 'high'),
  (39, 'cork', 'high'),
  (40, 'LivaEco Viscose', 'high'),
  (41, 'wool', 'high'),
  (42, 'LENZING™ ECOVERO™ Viscose', 'high'),
  (43, 'polyamide', 'low'),
  (44, 'spandex', 'low');


